apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: "server {
    \    listen       80;
    \    listen  [::]:80;
    \    location / {
    \        proxy_set_header Host $http_host;
    \        proxy_pass http://nginx-fluentd-wordpress;
    \        proxy_redirect ~^http://[^/]*/(.*) http://$http_host/$1;
    \    }
    }"
