apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    version: "1"
    app: wordpress
spec:
  containers:
    - name: wordpress
      image: wordpress:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: mssql-secret
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: mssql-secret
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              key: MYSQL_DATABASE
              name: mssql-secret
