apiVersion: v1
kind: Pod
metadata:
  name: nginx-fluentd
  labels:
    version: "1"
    app: nginx-fluentd
spec:
  containers:
    - name: nginx
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /var/log/nginx
          name: share-logs
        - mountPath: /etc/nginx/conf.d
          name: nginx-config
          readOnly: true
    - name: fluentd
      image: fluentd:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /logs
          name: share-logs
        - mountPath: /fluentd/etc
          name: fluentd-conf
          readOnly: true
  volumes:
    - name: share-logs
      emptyDir: {}
    - configMap:
        items:
          - key: default.conf
            path: default.conf
        name: nginx-config
      name: nginx-config
    - configMap:
        items:
          - key: fluent.conf
            path: fluent.conf
        name: fluentd-conf
      name: fluentd-conf
