apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
type: Opaque
data:
  MYSQL_DATABASE: dGVzdF9kYXRhYmFzZQ==
  MYSQL_PASSWORD: cGFzc3dvcmQ=
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  MYSQL_USER: dXNlcg==
